from django.urls import path
from .views import (
    iniciar_sesion, cerrar_sesion, registrarse, ver_dashboard, ver_proyectos, ver_detalle_proyecto,
    ver_tablero, ver_equipo, ver_servicios, ver_clientes, ver_areas, ver_especialidades,
    ver_reportes, ver_auditoria, ver_perfil, actualizar_estado_tarea, crear_tarea, editar_tarea, eliminar_tarea,
    ver_backlog, ver_sprints, ver_documentos, ver_tiempo, ver_calendario,
    ver_pendientes, ver_configuracion, crear_sprint, iniciar_sprint,
    completar_sprint, registrar_tiempo, subir_documento,
    crear_proyecto, editar_proyecto, eliminar_proyecto, comentar_proyecto,
    registrar_usuario, editar_usuario, desactivar_usuario, reactivar_usuario, ver_equipo_desactivados,
    crear_area, editar_area, eliminar_area,
    crear_especialidad, editar_especialidad, eliminar_especialidad,
    crear_cliente, editar_cliente, eliminar_cliente,
    crear_servicio, editar_servicio, eliminar_servicio,
    comentar_tarea, ver_notificaciones, marcar_notificacion_leida,
    marcar_todas_leidas, buscar,
    ver_suplencias, crear_suplencia, desactivar_suplencia,
    aprobar_registro, rechazar_registro,
    eliminar_documento,
    subir_documento_proyecto, eliminar_documento_proyecto,
    verificar_salud, verificar_disponibilidad,
    ver_mensajes, ver_conversacion, enviar_mensaje, buscar_usuarios,
    ver_portal_cliente, ver_detalle_proyecto_cliente, crear_solicitud_cliente,
    gestionar_miembros_proyecto,
)
from .views.wizard_views import (
    registro_paso1, registro_paso2, registro_paso3, registro_cancelar,
)
from .views.candidate_review_views import (
    candidato_detalle, candidato_save_checklist, candidato_decidir, cv_embed,
)
from .views.client_views import (
    ver_clientes, crear_cliente, editar_cliente, eliminar_cliente,
    client_detail, client_create_user, client_reset_password,
)

urlpatterns = [
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('solicitar-acceso/', registrarse, name='solicitar_acceso'),
    path('registrarse/', registrarse, name='registrarse'),
    path('registro/', registro_paso1, name='registro_paso1'),
    path('registro/paso-2/', registro_paso2, name='registro_paso2'),
    path('registro/paso-3/', registro_paso3, name='registro_paso3'),
    path('registro/cancelar/', registro_cancelar, name='registro_cancelar'),
    path('', ver_dashboard, name='ver_dashboard'),
    path('ver_proyectos/', ver_proyectos, name='ver_proyectos'),
    path('ver_proyectos/create/', crear_proyecto, name='crear_proyecto'),
    path('ver_proyectos/<int:pk>/', ver_detalle_proyecto, name='ver_detalle_proyecto'),
    path('ver_proyectos/<int:pk>/edit/', editar_proyecto, name='editar_proyecto'),
    path('ver_proyectos/<int:pk>/delete/', eliminar_proyecto, name='eliminar_proyecto'),
    path('ver_proyectos/<int:pk>/comment/', comentar_proyecto, name='comentar_proyecto'),
    path('ver_proyectos/<int:pk>/upload/', subir_documento_proyecto, name='subir_documento_proyecto'),
    path('ver_proyectos/<int:pk>/document/<int:doc_pk>/delete/', eliminar_documento_proyecto, name='eliminar_documento_proyecto'),
    path('ver_proyectos/<int:pk>/miembros/', gestionar_miembros_proyecto, name='gestionar_miembros_proyecto'),
    path('ver_tablero/', ver_tablero, name='ver_tablero'),
    path('ver_backlog/', ver_backlog, name='ver_backlog'),
    path('ver_sprints/', ver_sprints, name='ver_sprints'),
    path('ver_equipo/', ver_equipo, name='ver_equipo'),
    path('ver_equipo/create/', registrar_usuario, name='registrar_usuario'),
    path('ver_equipo/<int:pk>/edit/', editar_usuario, name='editar_usuario'),
    path('ver_equipo/<int:pk>/deactivate/', desactivar_usuario, name='desactivar_usuario'),
    path('ver_equipo/<int:pk>/reactivate/', reactivar_usuario, name='reactivar_usuario'),
    path('ver_equipo/desactivados/', ver_equipo_desactivados, name='ver_equipo_desactivados'),
    path('ver_servicios/', ver_servicios, name='ver_servicios'),
    path('ver_servicios/create/', crear_servicio, name='crear_servicio'),
    path('ver_servicios/<int:pk>/edit/', editar_servicio, name='editar_servicio'),
    path('ver_servicios/<int:pk>/delete/', eliminar_servicio, name='eliminar_servicio'),
    path('ver_clientes/', ver_clientes, name='ver_clientes'),
    path('ver_clientes/create/', crear_cliente, name='crear_cliente'),
    path('ver_clientes/<int:pk>/', client_detail, name='client_detail'),
    path('ver_clientes/<int:pk>/crear_usuario/', client_create_user, name='client_create_user'),
    path('ver_clientes/<int:pk>/reset_pw/<int:user_id>/', client_reset_password, name='client_reset_password'),
    path('ver_clientes/<int:pk>/edit/', editar_cliente, name='editar_cliente'),
    path('ver_clientes/<int:pk>/delete/', eliminar_cliente, name='eliminar_cliente'),
    path('ver_documentos/', ver_documentos, name='ver_documentos'),
    path('time-tracking/', ver_tiempo, name='ver_tiempo'),
    path('ver_calendario/', ver_calendario, name='ver_calendario'),
    path('ver_areas/', ver_areas, name='ver_areas'),
    path('ver_areas/create/', crear_area, name='crear_area'),
    path('ver_areas/<int:pk>/edit/', editar_area, name='editar_area'),
    path('ver_areas/<int:pk>/delete/', eliminar_area, name='eliminar_area'),
    path('ver_especialidades/', ver_especialidades, name='ver_especialidades'),
    path('ver_especialidades/create/', crear_especialidad, name='crear_especialidad'),
    path('ver_especialidades/<int:pk>/edit/', editar_especialidad, name='editar_especialidad'),
    path('ver_especialidades/<int:pk>/delete/', eliminar_especialidad, name='eliminar_especialidad'),
    path('ver_pendientes/', ver_pendientes, name='ver_pendientes'),
    path('pending/<int:pk>/approve/', aprobar_registro, name='aprobar_registro'),
    path('pending/<int:pk>/reject/', rechazar_registro, name='rechazar_registro'),
    path('pending/<int:pk>/review/', candidato_detalle, name='candidato_detalle'),
    path('pending/<int:pk>/checklist/', candidato_save_checklist, name='candidato_save_checklist'),
    path('pending/<int:pk>/decidir/', candidato_decidir, name='candidato_decidir'),
    path('pending/<int:pk>/cv/', cv_embed, name='cv_embed'),
    path('ver_configuracion/', ver_configuracion, name='ver_configuracion'),
    path('ver_reportes/', ver_reportes, name='ver_reportes'),
    path('ver_auditoria/', ver_auditoria, name='ver_auditoria'),
    path('ver_perfil/', ver_perfil, name='ver_perfil'),
    path('ver_notificaciones/', ver_notificaciones, name='ver_notificaciones'),
    path('notifications/<int:pk>/read/', marcar_notificacion_leida, name='marcar_notificacion_leida'),
    path('notifications/read-all/', marcar_todas_leidas, name='marcar_todas_leidas'),
    path('buscar/', buscar, name='buscar'),
    path('task/create/', crear_tarea, name='crear_tarea'),
    path('task/<int:pk>/edit/', editar_tarea, name='editar_tarea'),
    path('task/<int:pk>/delete/', eliminar_tarea, name='eliminar_tarea'),
    path('task/<int:pk>/status/', actualizar_estado_tarea, name='actualizar_estado_tarea'),
    path('task/<int:task_pk>/comment/', comentar_tarea, name='comentar_tarea'),
    path('sprint/create/', crear_sprint, name='crear_sprint'),
    path('sprint/<int:pk>/start/', iniciar_sprint, name='iniciar_sprint'),
    path('sprint/<int:pk>/complete/', completar_sprint, name='completar_sprint'),
    path('time-entry/create/', registrar_tiempo, name='registrar_tiempo'),
    path('document/upload/', subir_documento, name='subir_documento'),
    path('document/<int:pk>/delete/', eliminar_documento, name='eliminar_documento'),
    path('ver_suplencias/', ver_suplencias, name='ver_suplencias'),
    path('ver_suplencias/create/', crear_suplencia, name='crear_suplencia'),
    path('ver_suplencias/<int:pk>/deactivate/', desactivar_suplencia, name='desactivar_suplencia'),
    path('health/', verificar_salud, name='verificar_salud'),
    path('ready/', verificar_disponibilidad, name='verificar_disponibilidad'),
    path('mensajes/', ver_mensajes, name='ver_mensajes'),
    path('mensajes/<int:user_id>/', ver_conversacion, name='ver_conversacion'),
    path('mensajes/enviar/', enviar_mensaje, name='enviar_mensaje'),
    path('api/buscar-usuarios/', buscar_usuarios, name='buscar_usuarios'),
    path('portal/', ver_portal_cliente, name='ver_portal_cliente'),
    path('portal/proyecto/<int:pk>/', ver_detalle_proyecto_cliente, name='ver_detalle_proyecto_cliente'),
    path('portal/solicitud/nueva/', crear_solicitud_cliente, name='crear_solicitud_cliente'),
]
