# Generated by Django 6.0.5 on 2026-06-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_file_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='core.client'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('jefe-area', 'Jefe de Area'), ('jefe-proyecto', 'Jefe de Proyecto'), ('miembro', 'Miembro'), ('cliente', 'Cliente'), ('observer', 'Observador')], db_index=True, default='miembro', max_length=20),
        ),
    ]
