# Generated by Django 6.0.5 on 2026-06-12 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_client_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Lenguaje'), ('framework', 'Framework'), ('database', 'Base de datos'), ('tool', 'Herramienta'), ('platform', 'Plataforma'), ('other', 'Otro')], default='other', max_length=50)),
                ('icon', models.CharField(blank=True, default='fa-cog', max_length=50)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='La empresa sigue requiriéndola')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='specialty',
            name='icon',
            field=models.CharField(blank=True, default='fa-code', max_length=50),
        ),
        migrations.AddField(
            model_name='specialty',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoría padre (jerarquía)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.specialty'),
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='Ej: "Backend Developer con 3 años en Django"', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Resumen profesional')),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, help_text='PDF, DOC o DOCX. Máx 5MB.', null=True, upload_to='cvs/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('primary_specialty', models.ForeignKey(blank=True, help_text='Especialidad principal que el candidato declara', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_candidates', to='core.specialty')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_reviewed', to=settings.AUTH_USER_MODEL)),
                ('secondary_specialties', models.ManyToManyField(blank=True, help_text='Otras especialidades que también maneja', related_name='secondary_candidates', to='core.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Candidato',
                'verbose_name_plural': 'Perfiles de Candidatos',
            },
        ),
        migrations.CreateModel(
            name='CandidateTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2)),
                ('years_using', models.PositiveSmallIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidateprofile')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
            options={
                'verbose_name': 'Tecnología del candidato',
                'verbose_name_plural': 'Tecnologías del candidato',
                'unique_together': {('candidate', 'technology')},
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='candidates', through='core.CandidateTechnology', to='core.technology'),
        ),
    ]
