# Generated by Django 6.0.5 on 2026-06-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_technology_alter_specialty_options_specialty_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='checklist_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='checklist_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Checks marcados como validados (0-7)'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='review_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Checks de validacion del CV: {identidad, skills, experiencia, tecnologias, documentacion, portfolio}'),
        ),
    ]
