# Generated by Django 6.0.5 on 2026-06-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_candidateprofile_checklist_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='auto_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot automatico al subir el CV: {key: {value, confidence, evidence}}. El admin puede sobreescribirlo via review_checklist.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='auto_checklist_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='auto_checklist_avg_confidence',
            field=models.PositiveSmallIntegerField(default=0, help_text='Promedio de confianza de los 7 checks automaticos (0-100)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='review_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Checks de validacion del CV. Formato: {key: {value, confidence, evidence}}. Claves: identidad, cv_coherente, experiencia, tecnologias, documentacion, portfolio, red_flags.'),
        ),
    ]
