# Generated by Django 6.0.5 on 2026-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidateprofile_auto_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='auto_checklist',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='auto_checklist_at',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='auto_checklist_avg_confidence',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='checklist_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Checks marcados como validados (0-4)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='review_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Checks de validacion del CV marcados manualmente por el revisor. Claves: cv_coherente, experiencia, tecnologias, documentacion.'),
        ),
    ]
