# Generated by Django 6.0.5 on 2026-06-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registrationrequest'),
    ]

    operations = [
    ]
