# Generated by Django 6.0.5 on 2026-06-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20260616_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_temp/%Y/%m/'),
        ),
    ]
