# Generated by Django 6.0.5 on 2026-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_registrationrequest_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
