# Generated by Django 6.0.5 on 2026-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_registrationrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = archivado (soft delete)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = archivada (soft delete)'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('reviewing', 'En Revision'), ('in-progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de aprobacion'), ('active', 'Activo'), ('vacation', 'Vacaciones'), ('leave', 'Licencia'), ('dismissed', 'Desactivado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=20),
        ),
    ]
