# Generated by Django 6.0.5 on 2026-06-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_document_deleted_at_document_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = archivado (soft delete)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('planned', 'Planificado'), ('completed', 'Completado'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], db_index=True, default='planned', max_length=20),
        ),
    ]
