# Generated by Django 6.0.6 on 2026-06-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client_is_active_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
    ]
