# Generated by Django 6.0.6 on 2026-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_area_icon_remove_specialty_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('jefe-area', 'Jefe de Area'), ('jefe-proyecto', 'Jefe de Proyecto'), ('miembro', 'Miembro'), ('cliente', 'Cliente')], db_index=True, default='miembro', max_length=20),
        ),
    ]
