# Generated by Django 6.0.6 on 2026-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_observer_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLAN', 'Planificacion'), ('ACT', 'Activo'), ('CMP', 'Completado')], db_index=True, default='PLAN', max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Por Hacer'), ('PROG', 'En Progreso'), ('TEST', 'En Testing'), ('DONE', 'Completado')], db_index=True, default='TODO', max_length=4),
        ),
    ]
