# Generated by Django 6.0.6 on 2026-07-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_data_migrate_scrum_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.technology'),
        ),
    ]
