# Generated by Django 6.0.7 on 2026-07-09 23:06

from django.db import migrations


def add_leads_to_members(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.filter(lead__isnull=False):
        project.members.add(project.lead_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_active_session_key_userprofile_last_seen'),
    ]

    operations = [
        migrations.RunPython(add_leads_to_members, noop),
    ]
