# Generated by Django 6.0.7 on 2026-07-10 00:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_lead_is_member_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='color',
            field=models.CharField(default='#00bcd4', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#00bcd4', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='color',
            field=models.CharField(default='#00bcd4', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='#00bcd4', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal valido de 7 caracteres, ej: #00bcd4', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('task__isnull', False), ('project__isnull', False), _connector='OR'), name='comment_has_target'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACT')), fields=('project',), name='unique_active_sprint_per_project'),
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='substitution_end_after_start'),
        ),
    ]
