# Generated by Django 6.0.7 on 2026-07-10 01:02

import apps.core.infrastructure.models.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_area_color_alter_project_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='expires_at',
            field=models.DateTimeField(default=apps.core.infrastructure.models.models.default_registration_expiry),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
